apiVersion: v1
kind: Service
metadata:
    name: "myakscluster-8a44"
    labels:
        app: "myakscluster-8a44"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "myakscluster-8a44"