apiVersion: v1
kind: Service
metadata:
  name: ts
  namespace: namespace-workflow-1685935898903
spec:
  type: LoadBalancer
  selector:
    app: ts
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000